apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
data:
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: postgres:5432
  GITEA__database__NAME: gitea
  GITEA__database__USER: gitea
  GITEA__server__ROOT_URL: https://reynier124-kb.my.kube.um.edu.ar
